Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kvhnuke/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/kvhnuke/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 1072, in _main
    main()
  File "/home/kvhnuke/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 677, in main
    esp = esp or get_default_connected_device(
  File "/home/kvhnuke/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/__init__.py", line 961, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/home/kvhnuke/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 647, in connect
    last_error = self._connect_attempt(reset_strategy, mode)
  File "/home/kvhnuke/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/loader.py", line 532, in _connect_attempt
    reset_strategy()  # Reset the chip to bootloader (download mode)
  File "/home/kvhnuke/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/reset.py", line 89, in __call__
    self._setDTRandRTS(False, False)  # IO0=HIGH, done
  File "/home/kvhnuke/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esptool/reset.py", line 48, in _setDTRandRTS
    "I", fcntl.ioctl(self.port.fileno(), TIOCMGET, struct.pack("I", 0))
OSError: [Errno 5] Input/output error
CMake Error at run_serial_tool.cmake:66 (message):
  
  /home/kvhnuke/.espressif/python_env/idf5.2_py3.10_env/bin/python;;/home/kvhnuke/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s3
  failed.



